# Generated by Django 4.2.1 on 2023-06-14 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_dcb', '0005_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(default='f3f2a8ce-175a-4dbd-bd78-744d01b4a2be', on_delete=django.db.models.deletion.CASCADE, to='a_dcb.departments'),
        ),
    ]
